/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Model3.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Model3(props) {
  const { nodes, materials } = useGLTF('models/Model3.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.311}>
          <group name="8aa1db2a0e4a466485739256e58d1228fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Body006">
                  <group name="polySurface290">
                    <mesh name="polySurface290_Body_shd_0" geometry={nodes.polySurface290_Body_shd_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="polySurface291">
                    <mesh name="polySurface291_Body_shd_0" geometry={nodes.polySurface291_Body_shd_0.geometry} material={materials['Material.004']} />
                  </group>
                  <group name="Body007" position={[0, 2.649, -0.064]}>
                    <mesh name="Body_Body_shd_0005" geometry={nodes.Body_Body_shd_0005.geometry} material={materials['roof glass']} />
                    <mesh name="Body_Body_shd_0011" geometry={nodes.Body_Body_shd_0011.geometry} material={materials.glass} />
                    <mesh name="Body_Body_shd_0012" geometry={nodes.Body_Body_shd_0012.geometry} material={materials.lights} />
                    <mesh name="Body_Body_shd_0013" geometry={nodes.Body_Body_shd_0013.geometry} material={materials.blk} />
                    <mesh name="Body_Body_shd_0014" geometry={nodes.Body_Body_shd_0014.geometry} material={materials['roof glass']} />
                    <mesh name="Body_Body_shd_0015" geometry={nodes.Body_Body_shd_0015.geometry} material={materials.blk} />
                    <mesh name="Body_Body_shd_0020" geometry={nodes.Body_Body_shd_0020.geometry} material={materials.Tesla} />
                    <mesh name="Body_Body_shd_0021" geometry={nodes.Body_Body_shd_0021.geometry} material={materials.blk} />
                    <mesh name="Body_Body_shd_0022" geometry={nodes.Body_Body_shd_0022.geometry} material={materials.Tesla} />
                  </group>
                </group>
                <group name="Doors">
                  <group name="Doors001">
                    <group name="Front_door_L" position={[2.981, 2.162, 3.225]}>
                      <group name="Body008" position={[-0.15, 0.529, -2.149]}>
                        <mesh name="Body_Body_shd_0007" geometry={nodes.Body_Body_shd_0007.geometry} material={materials['roof glass']} />
                        <mesh name="Body_Body_shd_0018" geometry={nodes.Body_Body_shd_0018.geometry} material={materials.blk} />
                      </group>
                      <group name="Interior" position={[-0.406, -0.027, -2.066]}>
                        <mesh name="Interior_Interior_shd_0" geometry={nodes.Interior_Interior_shd_0.geometry} material={materials.Interior_shd} />
                      </group>
                    </group>
                    <group name="Front_door_R" position={[-2.981, 2.162, 3.225]}>
                      <group name="Body010" position={[0.15, 0.529, -2.149]}>
                        <mesh name="Body_Body_shd_0008" geometry={nodes.Body_Body_shd_0008.geometry} material={materials.glass} />
                        <mesh name="Body_Body_shd_0016" geometry={nodes.Body_Body_shd_0016.geometry} material={materials.blk} />
                      </group>
                      <group name="Interior001" position={[0.406, -0.027, -2.066]}>
                        <mesh name="Interior_Interior_shd_0001" geometry={nodes.Interior_Interior_shd_0001.geometry} material={materials.Interior_shd} />
                      </group>
                    </group>
                    <group name="Rear_door_L" position={[3.006, 2.248, -0.702]}>
                      <group name="Body009" position={[-0.321, 0.465, -1.837]}>
                        <mesh name="Body_Body_shd_0006" geometry={nodes.Body_Body_shd_0006.geometry} material={materials.glass} />
                        <mesh name="Body_Body_shd_0019" geometry={nodes.Body_Body_shd_0019.geometry} material={materials.blk} />
                      </group>
                      <group name="polySurface286" position={[-3.006, -2.248, 0.702]}>
                        <mesh name="polySurface286_Interior_shd_0" geometry={nodes.polySurface286_Interior_shd_0.geometry} material={materials.Interior_shd} />
                      </group>
                    </group>
                    <group name="Rear_door_R" position={[-3.006, 2.248, -0.702]}>
                      <group name="Body005" position={[0.321, 0.465, -1.837]}>
                        <mesh name="blades" geometry={nodes.blades.geometry} material={materials['Material.004']} />
                        <mesh geometry={nodes.Body.geometry}>
                          <meshStandardMaterial {...materials.BaseMtl} color={overlay == 1 || overlay == 13 ? (snap1.base.BaseMtl !== "none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
                            <canvasTexture
                              flipY={false}
                              wrapS={1000}
                              wrapT={1000}
                              colorSpace='srgb'
                              ref={textureRef}
                              attach="map"
                              image={canvasRef.current}
                            />
                          </meshStandardMaterial>
                        </mesh>
                        <mesh name="Body_Body_shd_0001" geometry={nodes.Body_Body_shd_0001.geometry} material={materials['Material.001']} />
                        <mesh name="Body_Body_shd_0002" geometry={nodes.Body_Body_shd_0002.geometry} material={materials['Material.001']} />
                        <mesh name="Body_Body_shd_0003" geometry={nodes.Body_Body_shd_0003.geometry} material={materials.blk} />

                        <mesh name="Body_Body_shd_0009" geometry={nodes.Body_Body_shd_0009.geometry} material={materials['Material.001']} />
                        <mesh name="Body_Body_shd_0010" geometry={nodes.Body_Body_shd_0010.geometry} material={materials.glass} />
                        <mesh name="Body_Body_shd_0017" geometry={nodes.Body_Body_shd_0017.geometry} material={materials.blk} />
                        <mesh name="dash" geometry={nodes.dash.geometry} material={materials.dash} />
                        <mesh name="nuts" geometry={nodes.nuts.geometry} material={materials.nuts} />
                        <mesh name="rim" geometry={nodes.rim.geometry} material={materials['Material.001']} />
                        <mesh name="underbelly" geometry={nodes.underbelly.geometry} material={materials['Material.001']} />
                        <mesh name="wipers" geometry={nodes.wipers.geometry} material={materials.blk} />
                      </group>
                      <group name="Interior002" position={[0.368, 0.001, -1.686]}>
                        <mesh name="Interior_Interior_shd_0002" geometry={nodes.Interior_Interior_shd_0002.geometry} material={materials.Interior_shd} />
                      </group>
                    </group>
                  </group>
                  <group name="Mechanics">
                    <group name="Front_mechanics_L">
                      <group name="polySurface260">
                        <mesh name="polySurface260_Body_shd_0" geometry={nodes.polySurface260_Body_shd_0.geometry} material={materials.Body_shd} />
                      </group>
                      <group name="Rotor">
                        <group name="polySurface277" position={[2.658, 1.967, 3.065]}>
                          <mesh name="polySurface277_Body_shd_0" geometry={nodes.polySurface277_Body_shd_0.geometry} material={materials.Body_shd} />
                        </group>
                        <group name="polySurface278" position={[2.658, 1.867, 2.712]}>
                          <mesh name="polySurface278_Body_shd_0" geometry={nodes.polySurface278_Body_shd_0.geometry} material={materials.Body_shd} />
                        </group>
                      </group>
                    </group>
                    <group name="Front_mechanics_R">
                      <group name="polySurface265">
                        <mesh name="polySurface265_Body_shd_0" geometry={nodes.polySurface265_Body_shd_0.geometry} material={materials.Body_shd} />
                      </group>
                      <group name="Rotor001">
                        <group name="polySurface279" position={[2.734, 2.181, -1.304]}>
                          <mesh name="polySurface279_Body_shd_0" geometry={nodes.polySurface279_Body_shd_0.geometry} material={materials.Body_shd} />
                        </group>
                        <group name="polySurface280" position={[2.734, 2.094, -0.795]}>
                          <mesh name="polySurface280_Body_shd_0" geometry={nodes.polySurface280_Body_shd_0.geometry} material={materials.Body_shd} />
                        </group>
                      </group>
                    </group>
                    <group name="Rear_mechanics_L">
                      <group name="polySurface275">
                        <mesh name="polySurface275_Body_shd_0" geometry={nodes.polySurface275_Body_shd_0.geometry} material={materials.Body_shd} />
                      </group>
                      <group name="Rotor003">
                        <group name="polySurface283" position={[-2.658, 1.867, 2.722]}>
                          <mesh name="polySurface283_Body_shd_0" geometry={nodes.polySurface283_Body_shd_0.geometry} material={materials.Body_shd} />
                        </group>
                        <group name="polySurface284" position={[-2.657, 1.945, 3.064]}>
                          <mesh name="polySurface284_Body_shd_0" geometry={nodes.polySurface284_Body_shd_0.geometry} material={materials.Body_shd} />
                        </group>
                      </group>
                    </group>
                    <group name="Rear_mechanics_R">
                      <group name="polySurface270">
                        <mesh name="polySurface270_Body_shd_0" geometry={nodes.polySurface270_Body_shd_0.geometry} material={materials.Body_shd} />
                      </group>
                      <group name="Rotor002">
                        <group name="polySurface281" position={[-2.734, 2.181, -1.304]}>
                          <mesh name="polySurface281_Body_shd_0" geometry={nodes.polySurface281_Body_shd_0.geometry} material={materials.Body_shd} />
                        </group>
                        <group name="polySurface282" position={[-2.734, 2.158, -0.795]}>
                          <mesh name="polySurface282_Body_shd_0" geometry={nodes.polySurface282_Body_shd_0.geometry} material={materials.Body_shd} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Interiors">
                  <group name="Interiors001" position={[0, 2.786, -1.418]}>
                    <mesh name="Interiors_Interior_shd_0" geometry={nodes.Interiors_Interior_shd_0.geometry} material={materials.blk} />
                  </group>
                </group>
                <group name="Lights">
                  <group name="Lights001" position={[0, 2.209, -0.137]}>
                    <mesh name="Lights_Lights_shd_0" geometry={nodes.Lights_Lights_shd_0.geometry} material={materials['Material.002']} />
                  </group>
                </group>
                <group name="Wheels">
                  <group name="Wheels001" position={[0, 1.159, 0.173]}>
                    <mesh name="Wheels_Tyres_shd_0" geometry={nodes.Wheels_Tyres_shd_0.geometry} material={materials.tires} />
                    <mesh name="Wheels_Tyres_shd_0001" geometry={nodes.Wheels_Tyres_shd_0001.geometry} material={materials.tires} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Model3.glb')
